name: "Homepage"
description: "Unofficial Homepage Add-on"
version: "0.9"
slug: "homepage"
init: false
arch:
  - aarch64
  - amd64
url: "https://github.com/Jonnyboy161/ha-repository/tree/main/homepage"
host_network: true
envoronment:
  HOMEPAGE_ALLOWED_HOSTS: "*"
ports:
  3000/tcp: 3000
map:
  - type: addon_config
    read_only: false
    path: /homepage/config
